In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Downloads/openpowerlifting.csv", engine='python')

In [3]:
subset_raw = data[['Name', 'Sex', 'Event', 'Age', 'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', 'AgeClass', 'Federation', 'Date', 'MeetCountry', 'MeetState', 'MeetName']]

In [4]:
subset_raw['Date'] = pd.to_datetime(subset_raw['Date']).dt.year

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [5]:
subset_SBD_USA = subset_raw[(subset_raw['Event']=='SBD')&(subset_raw['MeetCountry']=='USA')] 

subset_female2017 = subset_SBD_USA[(subset_SBD_USA['Sex']=='F')&(subset_SBD_USA['Date']==2017)]

In [6]:
subset_female2017_treated = subset_female2017.drop_duplicates(keep='first')

In [7]:
print(subset_female2017_treated.shape)

(35417, 13)

In [8]:
subset_female2017_treated['Name'].nunique()

16471

In [9]:
subset_female2017_treated['MeetState'].unique()

array(['NC', 'GA', 'MO', 'SC', 'IN', 'CA', 'NV', 'MI', 'AL', 'TX', 'OH',
       'AR', 'NJ', 'FL', 'MS', 'VT', 'UT', 'OR', 'NH', 'MA', 'WA', 'IL',
       'ME', 'IA', 'ID', nan, 'SD', 'ND', 'MN', 'NY', 'PA', 'TN', 'CT',
       'KS', 'CO', 'NM', 'AZ', 'OK', 'WI', 'VA', 'KY', 'MD', 'RI', 'LA',
       'AK', 'DC', 'DE', 'MT', 'NE', 'WV', 'WY', 'HI'], dtype=object)

In [10]:
subset_female2017_treated.groupby('MeetState').Name.nunique()

MeetState
AK      56
AL     108
AR      50
AZ     205
CA    1293
CO     247
CT     223
DC      26
DE      35
FL    1078
GA     243
HI      69
IA     178
ID      78
IL     379
IN      82
KS     114
KY     230
LA     215
MA     250
MD     219
ME      16
MI     167
MN     249
MO     178
MS      88
MT      43
NC     192
ND      28
NE      85
NH     129
NJ     372
NM      62
NV     345
NY     509
OH     540
OK      86
OR     191
PA     388
RI      43
SC     138
SD      40
TN     146
TX    7312
UT      71
VA     264
VT      38
WA     331
WI     430
WV      92
WY      78
Name: Name, dtype: int64

In [11]:
Northeast = ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA']
Midwest = ['IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD']
South = ['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX']
West = ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA']

In [12]:
def conditions(s):
    if s['MeetState'] in Northeast :
        return 'Northeast'
    elif s['MeetState'] in Midwest :
        return 'Midwest'
    elif s['MeetState'] in South :
        return 'South'
    else :
        return 'West'

In [13]:
subset_female2017_treated['Region'] = subset_female2017_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
subset_female2017_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region
302,Tiffany Bellamy,F,SBD,37.0,92.5,45.0,112.5,35-39,365Strong,2017,USA,NC,Charlotte Europa Games,South
303,Taylor Nugent,F,SBD,25.0,120.0,52.5,142.5,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South
304,Kayce Hoover,F,SBD,24.0,125.0,62.5,125.0,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South
305,Dawn Bogart,F,SBD,43.0,150.0,102.5,182.5,40-44,365Strong,2017,USA,NC,Charlotte Europa Games,South
307,Hanna Young,F,SBD,19.0,110.0,62.5,137.5,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South

In [15]:
Pacific = ['WA', 'OR', 'CA']
Mountain = ['MT', 'ID', 'WY', 'NV', 'UT', 'CO', 'AZ', 'NM']
WestNorthCentral = ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO']
WestSouthCentral = ['OK', 'TX', 'AR', 'LA']
EastNorthCentral = ['WI', 'MI', 'IL', 'IN', 'OH']
EastSouthCentral = ['KY', 'TN', 'MI', 'AL'] 
SouthAtlantic = ['WV', 'MD', 'DE', 'VA', 'NC', 'SC', 'GA', 'FL']
MiddleAtlantic = ['NY', 'PA', 'NJ']
NewEngland = ['ME', 'NH', 'VT', 'RI', 'MA', 'CT']

In [16]:
def conditions(s):
    if s['MeetState'] in Pacific :
        return 'Pacific'
    elif s['MeetState'] in Mountain :
        return 'Mountain'
    elif s['MeetState'] in WestNorthCentral :
        return 'WestNorthCentral'
    elif s['MeetState'] in WestSouthCentral :
        return 'WestSouthCentral'
    elif s['MeetState'] in EastNorthCentral :
        return 'EastNorthCentral'
    elif s['MeetState'] in EastSouthCentral :
        return 'EastSouthCentral'
    elif s['MeetState'] in SouthAtlantic :
        return 'SouthAtlantic'
    elif s['MeetState'] in MiddleAtlantic :
        return 'MiddleAtlantic'
    else :
        return 'NewEngland'

In [17]:
subset_female2017_treated['Division'] = subset_female2017_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [18]:
subset_female2017_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
302,Tiffany Bellamy,F,SBD,37.0,92.5,45.0,112.5,35-39,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
303,Taylor Nugent,F,SBD,25.0,120.0,52.5,142.5,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
304,Kayce Hoover,F,SBD,24.0,125.0,62.5,125.0,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
305,Dawn Bogart,F,SBD,43.0,150.0,102.5,182.5,40-44,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
307,Hanna Young,F,SBD,19.0,110.0,62.5,137.5,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic

In [19]:
subset_female2017_treated.tail()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
1343548,Alaina Hernandez,F,SBD,NaN,219.99,120.20,217.72,NaN,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343549,Jessica Bowersock,F,SBD,27.5,226.80,113.40,204.12,24-34,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343550,Kristen Wykoff,F,SBD,NaN,226.80,90.72,213.19,NaN,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343551,Cassandra Pinto,F,SBD,22.0,197.31,99.79,181.44,20-23,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343552,Jessica Chicke,F,SBD,36.5,181.44,104.33,181.44,35-39,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral

In [20]:
Red = ['ID', 'MT', 'WY', 'UT', 'AZ', 'ND', 'SD', 'NB', 'KS', 'OK', 'TX', 'MO', 'AR', 'LA', 'AL', 'MS', 'GA', 'SC', 'TN', 'WV', 'AK', 'KY']
Blue = ['WA', 'OR', 'CA', 'MN', 'IL', 'ME', 'VT', 'NH', 'NY', 'MA', 'NJ', 'RI', 'MD', 'DE', 'HI']
Pink = ['IN', 'NC']
Periwinkle = ['NV', 'CO', 'NM', 'WI', 'PA', 'VA']
Purple = ['IA', 'OH', 'FL']

In [21]:
def conditions(s):
    if s['MeetState'] in Red :
        return 'Red'
    elif s['MeetState'] in Blue :
        return 'Blue'
    elif s['MeetState'] in Pink :
        return 'Pink'
    elif s['MeetState'] in Periwinkle :
        return 'Periwinkle'
    else :
        return 'Purple'

In [22]:
subset_female2017_treated['Political'] = subset_female2017_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
subset_female2017_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division,Political
302,Tiffany Bellamy,F,SBD,37.0,92.5,45.0,112.5,35-39,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
303,Taylor Nugent,F,SBD,25.0,120.0,52.5,142.5,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
304,Kayce Hoover,F,SBD,24.0,125.0,62.5,125.0,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
305,Dawn Bogart,F,SBD,43.0,150.0,102.5,182.5,40-44,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
307,Hanna Young,F,SBD,19.0,110.0,62.5,137.5,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink

In [24]:
x = subset_female2017_treated[-subset_female2017_treated['MeetState'].isna()]

In [25]:
print(subset_female2017_treated.shape)

(35417, 16)

In [26]:
subset_female2017_treated.to_csv('subset_female2017_treated1.csv')