In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Downloads/openpowerlifting.csv", engine='python')

In [3]:
subset_raw = data[['Name', 'Sex', 'Event', 'Age', 'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', 'AgeClass', 'Federation', 'Date', 'MeetCountry', 'MeetState', 'MeetName']]

In [4]:
subset_raw['Date'] = pd.to_datetime(subset_raw['Date']).dt.year

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [5]:
subset_SBD_USA = subset_raw[(subset_raw['Event']=='SBD')&(subset_raw['MeetCountry']=='USA')] 

subset_female2018 = subset_SBD_USA[(subset_SBD_USA['Sex']=='F')&(subset_SBD_USA['Date']==2018)]

In [6]:
subset_female2018_treated = subset_female2018.drop_duplicates(keep='first')

In [7]:
print(subset_female2018_treated.shape)

(38248, 13)

In [8]:
subset_female2018_treated['Name'].nunique()

17881

In [9]:
subset_female2018_treated['MeetState'].unique()

array(['NC', 'GA', 'MO', 'IN', 'SC', 'NV', 'IA', 'MA', 'VT', 'WI', 'AR',
       'CO', 'MS', 'MD', 'TX', 'WA', 'MI', 'OH', 'SD', 'IL', nan, 'ND',
       'FL', 'ME', 'UT', 'ID', 'LA', 'MN', 'NY', 'TN', 'PA', 'CT', 'NM',
       'KY', 'OK', 'KS', 'CA', 'VA', 'AZ', 'NE', 'NJ', 'NH', 'AL', 'AK',
       'DC', 'DE', 'HI', 'MT', 'OR', 'RI', 'WV', 'WY'], dtype=object)

In [10]:
subset_female2018_treated.groupby('MeetState').Name.nunique()

MeetState
AK      42
AL     114
AR      98
AZ     299
CA    1394
CO     212
CT     279
DC      32
DE      13
FL     670
GA     269
HI      68
IA     194
ID      75
IL     396
IN     148
KS      99
KY     201
LA     235
MA     161
MD     209
ME      95
MI     225
MN     275
MO     344
MS      78
MT      48
NC     310
ND      40
NE      82
NH     162
NJ     356
NM      79
NV     351
NY     552
OH     543
OK      73
OR     246
PA     483
RI      52
SC     146
SD      55
TN     186
TX    7701
UT      81
VA     436
VT      35
WA     847
WI     632
WV     110
WY      40
Name: Name, dtype: int64

In [11]:
Northeast = ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA']
Midwest = ['IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD']
South = ['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX']
West = ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA']

In [12]:
def conditions(s):
    if s['MeetState'] in Northeast :
        return 'Northeast'
    elif s['MeetState'] in Midwest :
        return 'Midwest'
    elif s['MeetState'] in South :
        return 'South'
    else :
        return 'West'

In [13]:
subset_female2018_treated['Region'] = subset_female2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
subset_female2018_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region
787,Becca Dison,F,SBD,19.0,125.0,72.5,145.0,18-19,365Strong,2018,USA,NC,Enterprise Power Revolution,South
788,Andrea Fox,F,SBD,35.0,102.5,67.5,145.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South
789,Candace Locklear,F,SBD,23.0,152.5,72.5,172.5,20-23,365Strong,2018,USA,NC,Enterprise Power Revolution,South
790,Jennifer Broome,F,SBD,35.0,112.5,72.5,140.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South
791,Tara Peele,F,SBD,41.0,115.0,60.0,145.0,40-44,365Strong,2018,USA,NC,Enterprise Power Revolution,South

In [15]:
Pacific = ['WA', 'OR', 'CA']
Mountain = ['MT', 'ID', 'WY', 'NV', 'UT', 'CO', 'AZ', 'NM']
WestNorthCentral = ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO']
WestSouthCentral = ['OK', 'TX', 'AR', 'LA']
EastNorthCentral = ['WI', 'MI', 'IL', 'IN', 'OH']
EastSouthCentral = ['KY', 'TN', 'MI', 'AL'] 
SouthAtlantic = ['WV', 'MD', 'DE', 'VA', 'NC', 'SC', 'GA', 'FL']
MiddleAtlantic = ['NY', 'PA', 'NJ']
NewEngland = ['ME', 'NH', 'VT', 'RI', 'MA', 'CT']

In [16]:
def conditions(s):
    if s['MeetState'] in Pacific :
        return 'Pacific'
    elif s['MeetState'] in Mountain :
        return 'Mountain'
    elif s['MeetState'] in WestNorthCentral :
        return 'WestNorthCentral'
    elif s['MeetState'] in WestSouthCentral :
        return 'WestSouthCentral'
    elif s['MeetState'] in EastNorthCentral :
        return 'EastNorthCentral'
    elif s['MeetState'] in EastSouthCentral :
        return 'EastSouthCentral'
    elif s['MeetState'] in SouthAtlantic :
        return 'SouthAtlantic'
    elif s['MeetState'] in MiddleAtlantic :
        return 'MiddleAtlantic'
    else :
        return 'NewEngland'

In [17]:
subset_female2018_treated['Division'] = subset_female2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [18]:
subset_female2018_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
787,Becca Dison,F,SBD,19.0,125.0,72.5,145.0,18-19,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
788,Andrea Fox,F,SBD,35.0,102.5,67.5,145.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
789,Candace Locklear,F,SBD,23.0,152.5,72.5,172.5,20-23,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
790,Jennifer Broome,F,SBD,35.0,112.5,72.5,140.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
791,Tara Peele,F,SBD,41.0,115.0,60.0,145.0,40-44,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic

In [19]:
subset_female2018_treated.tail()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
1342564,Stephanie Smith,F,SBD,NaN,208.65,102.06,215.46,NaN,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342565,Barbara Coles,F,SBD,47.5,183.70,106.59,192.78,45-49,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342566,Jessica Bowersock,F,SBD,28.5,249.48,115.67,226.80,24-34,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342567,Alaina Hernandez,F,SBD,NaN,224.53,131.54,222.26,NaN,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342568,Jamie Kemper,F,SBD,32.5,238.14,129.27,215.46,24-34,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral

In [20]:
Red = ['ID', 'MT', 'WY', 'UT', 'AZ', 'ND', 'SD', 'NB', 'KS', 'OK', 'TX', 'MO', 'AR', 'LA', 'AL', 'MS', 'GA', 'SC', 'TN', 'WV', 'AK', 'KY']
Blue = ['WA', 'OR', 'CA', 'MN', 'IL', 'ME', 'VT', 'NH', 'NY', 'MA', 'NJ', 'RI', 'MD', 'DE', 'HI']
Pink = ['IN', 'NC']
Periwinkle = ['NV', 'CO', 'NM', 'WI', 'PA', 'VA']
Purple = ['IA', 'OH', 'FL']

In [21]:
def conditions(s):
    if s['MeetState'] in Red :
        return 'Red'
    elif s['MeetState'] in Blue :
        return 'Blue'
    elif s['MeetState'] in Pink :
        return 'Pink'
    elif s['MeetState'] in Periwinkle :
        return 'Periwinkle'
    else :
        return 'Purple'

In [22]:
subset_female2018_treated['Political'] = subset_female2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
subset_female2018_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division,Political
787,Becca Dison,F,SBD,19.0,125.0,72.5,145.0,18-19,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
788,Andrea Fox,F,SBD,35.0,102.5,67.5,145.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
789,Candace Locklear,F,SBD,23.0,152.5,72.5,172.5,20-23,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
790,Jennifer Broome,F,SBD,35.0,112.5,72.5,140.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
791,Tara Peele,F,SBD,41.0,115.0,60.0,145.0,40-44,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink

In [24]:
x = subset_female2018_treated[-subset_female2018_treated['MeetState'].isna()]

In [25]:
print(subset_female2018_treated.shape)

(38248, 16)

In [26]:
subset_female2018_treated.to_csv('subset_female2018_treated1.csv')