In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Downloads/openpowerlifting.csv", engine='python')

In [3]:
subset_raw = data[['Name', 'Sex', 'Event', 'Age', 'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', 'AgeClass', 'Federation', 'Date', 'MeetCountry', 'MeetState', 'MeetName']]

In [4]:
subset_raw['Date'] = pd.to_datetime(subset_raw['Date']).dt.year

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [5]:
subset_SBD_USA = subset_raw[(subset_raw['Event']=='SBD')&(subset_raw['MeetCountry']=='USA')] 

subset_male2017 = subset_SBD_USA[(subset_SBD_USA['Sex']=='M')&(subset_SBD_USA['Date']==2017)]

In [6]:
subset_male2017_treated = subset_male2017.drop_duplicates(keep='first')

In [7]:
print(subset_male2017_treated.shape)

(58951, 13)

In [8]:
subset_male2017_treated['Name'].nunique()

30813

In [9]:
subset_male2017_treated['MeetState'].unique()

array(['NC', 'GA', 'MO', 'SC', 'IN', 'CA', 'NV', 'AK', 'MI', 'AL', 'TX',
       'OH', 'AR', 'NJ', 'FL', 'MS', 'VT', 'UT', 'OR', 'NH', 'MA', 'WA',
       'IL', 'ME', 'IA', 'ID', nan, 'SD', 'ND', 'MN', 'NY', 'PA', 'TN',
       'CT', 'KS', 'CO', 'WI', 'NM', 'AZ', 'OK', 'VA', 'KY', 'MD', 'RI',
       'LA', 'DC', 'DE', 'MT', 'NE', 'WV', 'WY', 'HI'], dtype=object)

In [10]:
subset_male2017_treated.groupby('MeetState').Name.nunique()

MeetState
AK      129
AL      263
AR      194
AZ      357
CA     2489
CO      384
CT      360
DC       28
DE       58
FL     1768
GA      471
HI      146
IA      419
ID      112
IL      792
IN      237
KS      223
KY      493
LA      351
MA      606
MD      439
ME       59
MI      406
MN      404
MO      354
MS      257
MT       72
NC      421
ND       63
NE      148
NH      257
NJ      818
NM      120
NV      584
NY     1227
OH     1195
OK      246
OR      284
PA     1026
RI       97
SC      272
SD      106
TN      452
TX    12576
UT      136
VA      514
VT       67
WA      437
WI      579
WV      198
WY      126
Name: Name, dtype: int64

In [11]:
Northeast = ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA']
Midwest = ['IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD']
South = ['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX']
West = ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA']

In [12]:
def conditions(s):
    if s['MeetState'] in Northeast :
        return 'Northeast'
    elif s['MeetState'] in Midwest :
        return 'Midwest'
    elif s['MeetState'] in South :
        return 'South'
    else :
        return 'West'

In [13]:
subset_male2017_treated['Region'] = subset_male2017_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
subset_male2017_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region
332,Brannigan Coleman,M,SBD,27.0,172.5,130.0,217.5,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South
333,Haris Mian,M,SBD,19.0,120.0,77.5,165.0,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South
334,Collin Rausch,M,SBD,21.0,117.5,110.0,152.5,20-23,365Strong,2017,USA,NC,Charlotte Europa Games,South
335,Joseph Thomas,M,SBD,18.0,182.5,125.0,212.5,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South
336,Chris Macera,M,SBD,21.0,170.0,137.5,195.0,20-23,365Strong,2017,USA,NC,Charlotte Europa Games,South

In [15]:
Pacific = ['WA', 'OR', 'CA']
Mountain = ['MT', 'ID', 'WY', 'NV', 'UT', 'CO', 'AZ', 'NM']
WestNorthCentral = ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO']
WestSouthCentral = ['OK', 'TX', 'AR', 'LA']
EastNorthCentral = ['WI', 'MI', 'IL', 'IN', 'OH']
EastSouthCentral = ['KY', 'TN', 'MI', 'AL'] 
SouthAtlantic = ['WV', 'MD', 'DE', 'VA', 'NC', 'SC', 'GA', 'FL']
MiddleAtlantic = ['NY', 'PA', 'NJ']
NewEngland = ['ME', 'NH', 'VT', 'RI', 'MA', 'CT']

In [16]:
def conditions(s):
    if s['MeetState'] in Pacific :
        return 'Pacific'
    elif s['MeetState'] in Mountain :
        return 'Mountain'
    elif s['MeetState'] in WestNorthCentral :
        return 'WestNorthCentral'
    elif s['MeetState'] in WestSouthCentral :
        return 'WestSouthCentral'
    elif s['MeetState'] in EastNorthCentral :
        return 'EastNorthCentral'
    elif s['MeetState'] in EastSouthCentral :
        return 'EastSouthCentral'
    elif s['MeetState'] in SouthAtlantic :
        return 'SouthAtlantic'
    elif s['MeetState'] in MiddleAtlantic :
        return 'MiddleAtlantic'
    else :
        return 'NewEngland'

In [17]:
subset_male2017_treated['Division'] = subset_male2017_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [18]:
subset_male2017_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
332,Brannigan Coleman,M,SBD,27.0,172.5,130.0,217.5,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
333,Haris Mian,M,SBD,19.0,120.0,77.5,165.0,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
334,Collin Rausch,M,SBD,21.0,117.5,110.0,152.5,20-23,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
335,Joseph Thomas,M,SBD,18.0,182.5,125.0,212.5,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic
336,Chris Macera,M,SBD,21.0,170.0,137.5,195.0,20-23,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic

In [19]:
subset_male2017_treated.tail()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
1343586,Stephen Davis,M,SBD,NaN,285.76,222.26,340.19,NaN,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343587,Terrance Gilbert,M,SBD,27.5,322.05,183.70,310.71,24-34,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343588,Kevin McHugh,M,SBD,27.0,385.55,208.65,344.73,24-34,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343589,Patrick Vincent Maguire,M,SBD,NaN,362.87,242.67,288.03,NaN,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral
1343590,Doug Staley,M,SBD,27.5,347.00,185.97,306.17,24-34,XPC,2017,USA,OH,Finals,Midwest,EastNorthCentral

In [20]:
Red = ['ID', 'MT', 'WY', 'UT', 'AZ', 'ND', 'SD', 'NB', 'KS', 'OK', 'TX', 'MO', 'AR', 'LA', 'AL', 'MS', 'GA', 'SC', 'TN', 'WV', 'AK', 'KY']
Blue = ['WA', 'OR', 'CA', 'MN', 'IL', 'ME', 'VT', 'NH', 'NY', 'MA', 'NJ', 'RI', 'MD', 'DE', 'HI']
Pink = ['IN', 'NC']
Periwinkle = ['NV', 'CO', 'NM', 'WI', 'PA', 'VA']
Purple = ['IA', 'OH', 'FL']

In [21]:
def conditions(s):
    if s['MeetState'] in Red :
        return 'Red'
    elif s['MeetState'] in Blue :
        return 'Blue'
    elif s['MeetState'] in Pink :
        return 'Pink'
    elif s['MeetState'] in Periwinkle :
        return 'Periwinkle'
    else :
        return 'Purple'

In [22]:
subset_male2017_treated['Political'] = subset_male2017_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
subset_male2017_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division,Political
332,Brannigan Coleman,M,SBD,27.0,172.5,130.0,217.5,24-34,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
333,Haris Mian,M,SBD,19.0,120.0,77.5,165.0,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
334,Collin Rausch,M,SBD,21.0,117.5,110.0,152.5,20-23,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
335,Joseph Thomas,M,SBD,18.0,182.5,125.0,212.5,18-19,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink
336,Chris Macera,M,SBD,21.0,170.0,137.5,195.0,20-23,365Strong,2017,USA,NC,Charlotte Europa Games,South,SouthAtlantic,Pink

In [24]:
x = subset_male2017_treated[-subset_male2017_treated['MeetState'].isna()]

In [25]:
print(subset_male2017_treated.shape)

(58951, 16)

In [26]:
subset_male2017_treated.to_csv('subset_male2017_treated1.csv')