In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Downloads/openpowerlifting.csv", engine='python')

In [3]:
subset_raw = data[['Name', 'Sex', 'Event', 'Age', 'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', 'AgeClass', 'Federation', 'Date', 'MeetCountry', 'MeetState', 'MeetName']]

In [4]:
subset_raw['Date'] = pd.to_datetime(subset_raw['Date']).dt.year

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [5]:
subset_SBD_USA = subset_raw[(subset_raw['Event']=='SBD')&(subset_raw['MeetCountry']=='USA')] 

subset_male2018 = subset_SBD_USA[(subset_SBD_USA['Sex']=='M')&(subset_SBD_USA['Date']==2018)]

In [6]:
subset_male2018_treated = subset_male2018.drop_duplicates(keep='first')

In [7]:
print(subset_male2018_treated.shape)

(60086, 13)

In [8]:
subset_male2018_treated['Name'].nunique()

32311

In [9]:
subset_male2018_treated['MeetState'].unique()

array(['NC', 'GA', 'MO', 'IN', 'SC', 'NV', 'IA', 'VA', 'MA', 'VT', 'WI',
       'AR', 'CO', 'MS', 'MD', 'TX', 'WA', 'MI', 'OH', 'SD', 'IL', nan,
       'ND', 'FL', 'UT', 'ID', 'ME', 'LA', 'MN', 'NY', 'TN', 'PA', 'CT',
       'NM', 'KY', 'OK', 'KS', 'CA', 'AZ', 'NE', 'NJ', 'NH', 'AL', 'AK',
       'DC', 'DE', 'HI', 'MT', 'OR', 'RI', 'WV', 'WY'], dtype=object)

In [10]:
subset_male2018_treated.groupby('MeetState').Name.nunique()

MeetState
AK       80
AL      326
AR      199
AZ      523
CA     2686
CO      346
CT      511
DC       41
DE       37
FL     1281
GA      530
HI      165
IA      393
ID      116
IL      833
IN      336
KS      231
KY      525
LA      427
MA      440
MD      399
ME      144
MI      484
MN      414
MO      504
MS      184
MT       61
NC      727
ND       75
NE      141
NH      260
NJ      769
NM      185
NV      564
NY     1098
OH     1150
OK      144
OR      349
PA     1142
RI       90
SC      306
SD      133
TN      539
TX    12432
UT      122
VA      985
VT       66
WA     1162
WI      844
WV      281
WY       94
Name: Name, dtype: int64

In [11]:
Northeast = ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA']
Midwest = ['IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD']
South = ['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX']
West = ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA']

In [12]:
def conditions(s):
    if s['MeetState'] in Northeast :
        return 'Northeast'
    elif s['MeetState'] in Midwest :
        return 'Midwest'
    elif s['MeetState'] in South :
        return 'South'
    else :
        return 'West'

In [13]:
subset_male2018_treated['Region'] = subset_male2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
subset_male2018_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region
796,Chris Blanchard,M,SBD,40.0,125.0,115.0,177.5,40-44,365Strong,2018,USA,NC,Enterprise Power Revolution,South
797,Joe Plyler,M,SBD,55.0,160.0,115.0,197.5,55-59,365Strong,2018,USA,NC,Enterprise Power Revolution,South
798,Jayson Hamilton,M,SBD,36.0,165.0,122.5,200.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South
801,Rocky Hall,M,SBD,27.0,215.0,150.0,252.5,24-34,365Strong,2018,USA,NC,Enterprise Power Revolution,South
802,Adrian Sullivan,M,SBD,27.0,195.0,160.0,227.5,24-34,365Strong,2018,USA,NC,Enterprise Power Revolution,South

In [15]:
Pacific = ['WA', 'OR', 'CA']
Mountain = ['MT', 'ID', 'WY', 'NV', 'UT', 'CO', 'AZ', 'NM']
WestNorthCentral = ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO']
WestSouthCentral = ['OK', 'TX', 'AR', 'LA']
EastNorthCentral = ['WI', 'MI', 'IL', 'IN', 'OH']
EastSouthCentral = ['KY', 'TN', 'MI', 'AL'] 
SouthAtlantic = ['WV', 'MD', 'DE', 'VA', 'NC', 'SC', 'GA', 'FL']
MiddleAtlantic = ['NY', 'PA', 'NJ']
NewEngland = ['ME', 'NH', 'VT', 'RI', 'MA', 'CT']

In [16]:
def conditions(s):
    if s['MeetState'] in Pacific :
        return 'Pacific'
    elif s['MeetState'] in Mountain :
        return 'Mountain'
    elif s['MeetState'] in WestNorthCentral :
        return 'WestNorthCentral'
    elif s['MeetState'] in WestSouthCentral :
        return 'WestSouthCentral'
    elif s['MeetState'] in EastNorthCentral :
        return 'EastNorthCentral'
    elif s['MeetState'] in EastSouthCentral :
        return 'EastSouthCentral'
    elif s['MeetState'] in SouthAtlantic :
        return 'SouthAtlantic'
    elif s['MeetState'] in MiddleAtlantic :
        return 'MiddleAtlantic'
    else :
        return 'NewEngland'

In [17]:
subset_male2018_treated['Division'] = subset_male2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [18]:
subset_male2018_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
796,Chris Blanchard,M,SBD,40.0,125.0,115.0,177.5,40-44,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
797,Joe Plyler,M,SBD,55.0,160.0,115.0,197.5,55-59,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
798,Jayson Hamilton,M,SBD,36.0,165.0,122.5,200.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
801,Rocky Hall,M,SBD,27.0,215.0,150.0,252.5,24-34,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic
802,Adrian Sullivan,M,SBD,27.0,195.0,160.0,227.5,24-34,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic

In [19]:
subset_male2018_treated.tail()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
1342591,JP Carroll,M,SBD,37.5,426.38,254.01,353.80,35-39,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342592,Kevin McHugh,M,SBD,28.0,410.50,213.19,328.85,24-34,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342593,Garrett Denham,M,SBD,33.5,367.41,222.26,333.39,24-34,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342594,Bill Lee,M,SBD,33.5,340.19,199.58,324.32,24-34,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral
1342595,Benjamin Dewig,M,SBD,NaN,317.51,172.37,340.19,NaN,XPC,2018,USA,OH,Finals,Midwest,EastNorthCentral

In [20]:
Red = ['ID', 'MT', 'WY', 'UT', 'AZ', 'ND', 'SD', 'NB', 'KS', 'OK', 'TX', 'MO', 'AR', 'LA', 'AL', 'MS', 'GA', 'SC', 'TN', 'WV', 'AK', 'KY']
Blue = ['WA', 'OR', 'CA', 'MN', 'IL', 'ME', 'VT', 'NH', 'NY', 'MA', 'NJ', 'RI', 'MD', 'DE', 'HI']
Pink = ['IN', 'NC']
Periwinkle = ['NV', 'CO', 'NM', 'WI', 'PA', 'VA']
Purple = ['IA', 'OH', 'FL']

In [21]:
def conditions(s):
    if s['MeetState'] in Red :
        return 'Red'
    elif s['MeetState'] in Blue :
        return 'Blue'
    elif s['MeetState'] in Pink :
        return 'Pink'
    elif s['MeetState'] in Periwinkle :
        return 'Periwinkle'
    else :
        return 'Purple'

In [22]:
subset_male2018_treated['Political'] = subset_male2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
subset_male2018_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division,Political
796,Chris Blanchard,M,SBD,40.0,125.0,115.0,177.5,40-44,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
797,Joe Plyler,M,SBD,55.0,160.0,115.0,197.5,55-59,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
798,Jayson Hamilton,M,SBD,36.0,165.0,122.5,200.0,35-39,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
801,Rocky Hall,M,SBD,27.0,215.0,150.0,252.5,24-34,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink
802,Adrian Sullivan,M,SBD,27.0,195.0,160.0,227.5,24-34,365Strong,2018,USA,NC,Enterprise Power Revolution,South,SouthAtlantic,Pink

In [24]:
x = subset_male2018_treated[-subset_male2018_treated['MeetState'].isna()]

In [25]:
print(subset_male2018_treated.shape)

(60086, 16)

In [26]:
subset_male2018_treated.to_csv('subset_male2018_treated1.csv')