In [1]:
import pandas as pd

# 1. Importing Pandas Library

Running this cell will retrieve the Pandas Library in Python.

In [2]:
data = pd.read_csv("Downloads/openpowerlifting.csv", engine='python')

# 2. Importing a CSV

Running this cell will execute the following: treating the csv file as a data variable that is being read in via the Pandas Library with the specific file path from your computer or local device as the location to retrieve the csv from using the Python engine.

In [3]:
subset_raw = data[['Name', 'Sex', 'Event', 'Age', 'Best3SquatKg', 'Best3BenchKg', 'Best3DeadliftKg', 'AgeClass', 'Federation', 'Date', 'MeetCountry', 'MeetState', 'MeetName']]

# 3. Selecting Columns from Dataset

Running this cell will save the previously run data as a new dataset **subset_raw** because not all columns from the original dataset/csv are being retrieved. From **subset_raw** it refers back to the previous data variable and then, within the double brackets are the names of the columns to be selected from the original dataset and included in **subset_raw**.

In [4]:
subset_raw['Date'] = pd.to_datetime(subset_raw['Date']).dt.year

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

# 4. Transforming the Date Column

Running this cell will retrieve the new **subset_raw** dataset and look at the *Date* column. Within the *Date* column, the pandas library is transforming the current $datetime$ format to $year$ only in the **subset_raw** dataset.

In [5]:
subset_SBD_USA = subset_raw[(subset_raw['Event']=='SBD')&(subset_raw['MeetCountry']=='USA')] 

subset_female2016 = subset_SBD_USA[(subset_SBD_USA['Sex']=='F')&(subset_SBD_USA['Date']==2016)] 
subset_female2017 = subset_SBD_USA[(subset_SBD_USA['Sex']=='F')&(subset_SBD_USA['Date']==2017)] 
subset_female2018 = subset_SBD_USA[(subset_SBD_USA['Sex']=='F')&(subset_SBD_USA['Date']==2018)] 

subset_male2016 = subset_SBD_USA[(subset_SBD_USA['Sex']=='M')&(subset_SBD_USA['Date']==2016)] 
subset_male2017 = subset_SBD_USA[(subset_SBD_USA['Sex']=='M')&(subset_SBD_USA['Date']==2017)] 
subset_male2018 = subset_SBD_USA[(subset_SBD_USA['Sex']=='M')&(subset_SBD_USA['Date']==2018)]

# 5. Creating Subsets from the Superset

Running this cell will create seven separate subsets. 

*First subset* is **subset_SBD_USA** and references **subset_raw** dataset as the one to code and again inside the bracket and parentheses as the dataset to transform. Then, for the *Event* column it wants only the rows with the value *SBD* and in the *MeetCountry* column only the rows with the value *USA*.  This first subset is applied to the subsequent datasets as these are row values to be selected for all six subsets that follow.

The three **subset_male** datasets are each differentiated in variable name by the calendar year. These subsets refer to the former **subset_SBD_USA** and again within the bracket and parentheses to be transformed where the *Sex* column retrieves row values for *M* $male$ and *Date* column where row value is *2016*, *2017*, and *2018*. 

The next three **subset_female** are done in the same way except where the *Sex* column is referred to the row value being retrieved is *F* $female$.

In [6]:
subset_female2016_treated = subset_female2016.drop_duplicates(keep='first') 
subset_female2017_treated = subset_female2017.drop_duplicates(keep='first')
subset_female2018_treated = subset_female2018.drop_duplicates(keep='first')
subset_male2016_treated = subset_male2016.drop_duplicates(keep='first')
subset_male2017_treated = subset_male2017.drop_duplicates(keep='first')
subset_male2018_treated = subset_male2018.drop_duplicates(keep='first')

# 6. Dropping Duplicates Row Values

Running this cell will drop duplication of participant names and keep the first occurrence of the name.  The six subsets are each given a new variable name *treated* was added to differentiate. Then, within each subset the former subset name is referred and the dot notation $dropduplicates$ function is appended with keeping the first occurrence of each.

In [7]:
print(subset_female2016_treated.shape)
print(subset_female2017_treated.shape)
print(subset_female2018_treated.shape)
print(subset_male2016_treated.shape)
print(subset_male2017_treated.shape)
print(subset_male2018_treated.shape)

(32429, 13)
(35417, 13)
(38248, 13)
(56199, 13)
(58951, 13)
(60086, 13)

# 7. Testing the Drop Duplicates Function

Each of the *treated* subsets are printed with the dot notation $shape$ function appended to show the number of rows and columns in each subset. These numbers are different from the original -- less than, so we know that the $drop duplicates$ function removed rows.

The dot notation $shape$ is used later in the Notebook to test the number of rows and columns modified.

In [8]:
print(subset_female2016_treated['Name'].nunique())
print(subset_female2017_treated['Name'].nunique())
print(subset_female2018_treated['Name'].nunique())
print(subset_male2016_treated['Name'].nunique())
print(subset_male2017_treated['Name'].nunique())
print(subset_male2018_treated['Name'].nunique())

14826
16471
17881
29088
30813
32311

# 8. Getting total of unique values in a column

Running this cell will show that the singular subset **subset_female2016_treated** with the column *Name* and appended dot notation $nunique$ shows how many rows for that column are unique.

In [9]:
subset_female2016_treated['MeetState'].unique()
subset_female2017_treated['MeetState'].unique()
subset_female2018_treated['MeetState'].unique()
subset_male2016_treated['MeetState'].unique()
subset_male2017_treated['MeetState'].unique()
subset_male2018_treated['MeetState'].unique()

array(['NC', 'GA', 'MO', 'IN', 'SC', 'NV', 'IA', 'VA', 'MA', 'VT', 'WI',
       'AR', 'CO', 'MS', 'MD', 'TX', 'WA', 'MI', 'OH', 'SD', 'IL', nan,
       'ND', 'FL', 'UT', 'ID', 'ME', 'LA', 'MN', 'NY', 'TN', 'PA', 'CT',
       'NM', 'KY', 'OK', 'KS', 'CA', 'AZ', 'NE', 'NJ', 'NH', 'AL', 'AK',
       'DC', 'DE', 'HI', 'MT', 'OR', 'RI', 'WV', 'WY'], dtype=object)

# 9. Listing Unique Values for a Column

Running this cell will list the unique values for the *MeetState* column within the **subset_female2016_treated** subset and identify the data type.

In [10]:
subset_female2016_treated.groupby('MeetState').Name.nunique()

MeetState
AK      61
AL      75
AR      21
AZ     158
CA    1068
CO     258
CT     145
FL     442
GA     611
HI      66
IA     146
ID      77
IL     352
IN      82
KS      71
KY     118
LA     229
MA     125
MD     144
ME      25
MI     176
MN     224
MO     162
MS      49
MT      24
NC     168
ND      16
NE      68
NH      78
NJ     282
NM      70
NV     305
NY     479
OH     424
OK      96
OR     190
PA     444
RI     131
SC      61
SD      19
TN      99
TX    7075
UT      48
VA     201
VT      37
WA     271
WI     360
WV     107
WY      49
Name: Name, dtype: int64

In [11]:
subset_female2017_treated.groupby('MeetState').Name.nunique()

MeetState
AK      56
AL     108
AR      50
AZ     205
CA    1293
CO     247
CT     223
DC      26
DE      35
FL    1078
GA     243
HI      69
IA     178
ID      78
IL     379
IN      82
KS     114
KY     230
LA     215
MA     250
MD     219
ME      16
MI     167
MN     249
MO     178
MS      88
MT      43
NC     192
ND      28
NE      85
NH     129
NJ     372
NM      62
NV     345
NY     509
OH     540
OK      86
OR     191
PA     388
RI      43
SC     138
SD      40
TN     146
TX    7312
UT      71
VA     264
VT      38
WA     331
WI     430
WV      92
WY      78
Name: Name, dtype: int64

In [12]:
subset_female2018_treated.groupby('MeetState').Name.nunique()

MeetState
AK      42
AL     114
AR      98
AZ     299
CA    1394
CO     212
CT     279
DC      32
DE      13
FL     670
GA     269
HI      68
IA     194
ID      75
IL     396
IN     148
KS      99
KY     201
LA     235
MA     161
MD     209
ME      95
MI     225
MN     275
MO     344
MS      78
MT      48
NC     310
ND      40
NE      82
NH     162
NJ     356
NM      79
NV     351
NY     552
OH     543
OK      73
OR     246
PA     483
RI      52
SC     146
SD      55
TN     186
TX    7701
UT      81
VA     436
VT      35
WA     847
WI     632
WV     110
WY      40
Name: Name, dtype: int64

In [13]:
subset_male2016_treated.groupby('MeetState').Name.nunique()

MeetState
AK      215
AL      182
AR       76
AZ      321
CA     2091
CO      415
CT      280
FL      929
GA     1012
HI      125
IA      403
ID      138
IL      752
IN      225
KS      172
KY      352
LA      461
MA      365
MD      337
ME       82
MI      448
MN      344
MO      325
MS      180
MT       47
NC      379
ND       50
NE      193
NH      146
NJ      778
NM      129
NV      557
NY     1222
OH     1003
OK      232
OR      282
PA     1083
RI      275
SC      122
SD       45
TN      341
TX    12336
UT       92
VA      404
VT       64
WA      479
WI      447
WV      218
WY       89
Name: Name, dtype: int64

In [14]:
subset_male2017_treated.groupby('MeetState').Name.nunique()

MeetState
AK      129
AL      263
AR      194
AZ      357
CA     2489
CO      384
CT      360
DC       28
DE       58
FL     1768
GA      471
HI      146
IA      419
ID      112
IL      792
IN      237
KS      223
KY      493
LA      351
MA      606
MD      439
ME       59
MI      406
MN      404
MO      354
MS      257
MT       72
NC      421
ND       63
NE      148
NH      257
NJ      818
NM      120
NV      584
NY     1227
OH     1195
OK      246
OR      284
PA     1026
RI       97
SC      272
SD      106
TN      452
TX    12576
UT      136
VA      514
VT       67
WA      437
WI      579
WV      198
WY      126
Name: Name, dtype: int64

In [15]:
subset_male2018_treated.groupby('MeetState').Name.nunique()

MeetState
AK       80
AL      326
AR      199
AZ      523
CA     2686
CO      346
CT      511
DC       41
DE       37
FL     1281
GA      530
HI      165
IA      393
ID      116
IL      833
IN      336
KS      231
KY      525
LA      427
MA      440
MD      399
ME      144
MI      484
MN      414
MO      504
MS      184
MT       61
NC      727
ND       75
NE      141
NH      260
NJ      769
NM      185
NV      564
NY     1098
OH     1150
OK      144
OR      349
PA     1142
RI       90
SC      306
SD      133
TN      539
TX    12432
UT      122
VA      985
VT       66
WA     1162
WI      844
WV      281
WY       94
Name: Name, dtype: int64

# 10. Grouping Row Values and Getting a Total of Values

The six cells above are doing the same functions for each subset individually. Running the cells uses the dot notation $groupby$ function which groups *MeetState* column by the **Name** of the row value and then provides the total number of $unique$ values for each **Name**.

In [16]:
Northeast = ['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA']
Midwest = ['IL', 'IN', 'MI', 'OH', 'WI', 'IA', 'KS', 'MN', 'MO', 'NE', 'ND', 'SD']
South = ['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX']
West = ['AZ', 'CO', 'ID', 'MT', 'NV', 'NM', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA']

# 11. Creating Lists with Row Values

Running the cell above assigns row values for the *MeetState* column into lists/categories.

In [17]:
def conditions(s):
    if s['MeetState'] in Northeast :
        return 'Northeast'
    elif s['MeetState'] in Midwest :
        return 'Midwest'
    elif s['MeetState'] in South :
        return 'South'
    else :
        return 'West'

# 12. Using a Decision Tree for List Parameters

Running the cell above will sort each row value for the *MeetState* column into its associated list after meeting conditions that are $true$. For example, a **South** state like "DE" or Delaware will be $false$ for **Northeast**, $false$ for **Midwest**, but $true$ for **South**.

Decision trees are used further down in the Notebook for the insertion of the *Division* and *Political* columns.

In [18]:
subset_female2016_treated['Region'] = subset_female2016_treated.apply(conditions, axis=1)
subset_female2017_treated['Region'] = subset_female2017_treated.apply(conditions, axis=1)
subset_female2018_treated['Region'] = subset_female2018_treated.apply(conditions, axis=1)
subset_male2016_treated['Region'] = subset_male2016_treated.apply(conditions, axis=1)
subset_male2017_treated['Region'] = subset_male2017_treated.apply(conditions, axis=1)
subset_male2018_treated['Region'] = subset_male2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

# 13. Inserting a New Column

In the cell above, each **treated** subset is having a column name *Region* being appended to the far right in the table as indicated with the $axis$ position. The previous conditions set forth in the decision tree are referenced and must be met for each row being added to the new column. 

This is done again further down with the *Division* column and *Political* column.

In [19]:
print(subset_female2016_treated.head())
print(subset_female2017_treated.head())
print(subset_female2018_treated.head())
print(subset_male2016_treated.head())
print(subset_male2017_treated.head())
print(subset_male2018_treated.head())

                     Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
0        Angie Belk Terry   F   SBD  47.0         47.63         20.41
1             Dawn Bogart   F   SBD  42.0        142.88         95.25
5         Courtney Norris   F   SBD  28.0        170.10         77.11
6           Maureen Clary   F   SBD  60.0        124.74         95.25
8  Priscilla Sweat Pardue   F   SBD  52.0        120.20         54.43

   Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
0            70.31    45-49  365Strong  2016         USA        NC
1           163.29    40-44  365Strong  2016         USA        NC
5           145.15    24-34  365Strong  2016         USA        NC
6           163.29    60-64  365Strong  2016         USA        NC
8           108.86    50-54  365Strong  2016         USA        NC

                                            MeetName Region
0  Junior & Senior National Powerlifting Champion...  South
1  Junior & Senior National Powerlifting Champion...  South
5  Junior & Senior National Powerlifting Champion...  South
6  Junior & Senior National Powerlifting Champion...  South
8  Junior & Senior National Powerlifting Champion...  South
                Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
302  Tiffany Bellamy   F   SBD  37.0          92.5          45.0
303    Taylor Nugent   F   SBD  25.0         120.0          52.5
304     Kayce Hoover   F   SBD  24.0         125.0          62.5
305      Dawn Bogart   F   SBD  43.0         150.0         102.5
307      Hanna Young   F   SBD  19.0         110.0          62.5

     Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
302            112.5    35-39  365Strong  2017         USA        NC
303            142.5    24-34  365Strong  2017         USA        NC
304            125.0    24-34  365Strong  2017         USA        NC
305            182.5    40-44  365Strong  2017         USA        NC
307            137.5    18-19  365Strong  2017         USA        NC

                   MeetName Region
302  Charlotte Europa Games  South
303  Charlotte Europa Games  South
304  Charlotte Europa Games  South
305  Charlotte Europa Games  South
307  Charlotte Europa Games  South
                 Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
787       Becca Dison   F   SBD  19.0         125.0          72.5
788        Andrea Fox   F   SBD  35.0         102.5          67.5
789  Candace Locklear   F   SBD  23.0         152.5          72.5
790   Jennifer Broome   F   SBD  35.0         112.5          72.5
791        Tara Peele   F   SBD  41.0         115.0          60.0

     Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
787            145.0    18-19  365Strong  2018         USA        NC
788            145.0    35-39  365Strong  2018         USA        NC
789            172.5    20-23  365Strong  2018         USA        NC
790            140.0    35-39  365Strong  2018         USA        NC
791            145.0    40-44  365Strong  2018         USA        NC

                        MeetName Region
787  Enterprise Power Revolution  South
788  Enterprise Power Revolution  South
789  Enterprise Power Revolution  South
790  Enterprise Power Revolution  South
791  Enterprise Power Revolution  South
               Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
23  Kevin Gingerich   M   SBD  32.0        154.22        115.67
24       Juan Bollo   M   SBD  20.0        163.29        111.13
25    James McManus   M   SBD  36.0           NaN           NaN
27  Scott Faircloth   M   SBD  27.0        181.44         99.79
28      Justin Monk   M   SBD  22.0        161.03        127.01

    Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
23           183.70    24-34  365Strong  2016         USA        NC
24           204.12    20-23  365Strong  2016         USA        NC
25              NaN    35-39  365Strong  2016         USA        NC
27           188.24    24-34  365Strong  2016         USA        NC
28           197.31    20-23  365Strong  2016         USA        NC

                                             MeetName Region
23  Junior & Senior National Powerlifting Champion...  South
24  Junior & Senior National Powerlifting Champion...  South
25  Junior & Senior National Powerlifting Champion...  South
27  Junior & Senior National Powerlifting Champion...  South
28  Junior & Senior National Powerlifting Champion...  South
                  Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
332  Brannigan Coleman   M   SBD  27.0         172.5         130.0
333         Haris Mian   M   SBD  19.0         120.0          77.5
334      Collin Rausch   M   SBD  21.0         117.5         110.0
335      Joseph Thomas   M   SBD  18.0         182.5         125.0
336       Chris Macera   M   SBD  21.0         170.0         137.5

     Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
332            217.5    24-34  365Strong  2017         USA        NC
333            165.0    18-19  365Strong  2017         USA        NC
334            152.5    20-23  365Strong  2017         USA        NC
335            212.5    18-19  365Strong  2017         USA        NC
336            195.0    20-23  365Strong  2017         USA        NC

                   MeetName Region
332  Charlotte Europa Games  South
333  Charlotte Europa Games  South
334  Charlotte Europa Games  South
335  Charlotte Europa Games  South
336  Charlotte Europa Games  South
                Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
796  Chris Blanchard   M   SBD  40.0         125.0         115.0
797       Joe Plyler   M   SBD  55.0         160.0         115.0
798  Jayson Hamilton   M   SBD  36.0         165.0         122.5
801       Rocky Hall   M   SBD  27.0         215.0         150.0
802  Adrian Sullivan   M   SBD  27.0         195.0         160.0

     Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
796            177.5    40-44  365Strong  2018         USA        NC
797            197.5    55-59  365Strong  2018         USA        NC
798            200.0    35-39  365Strong  2018         USA        NC
801            252.5    24-34  365Strong  2018         USA        NC
802            227.5    24-34  365Strong  2018         USA        NC

                        MeetName Region
796  Enterprise Power Revolution  South
797  Enterprise Power Revolution  South
798  Enterprise Power Revolution  South
801  Enterprise Power Revolution  South
802  Enterprise Power Revolution  South

# 14. Testing the Added Column

Running the cell above will print the first five rows with the dot notation $head$ in each subset and you'll see that the *Region* column has been added to each subset. Testing is being done in the cell below using the dot notation $tail$ which prints the last five rows in each subset.

In [20]:
print(subset_female2016_treated.tail())
print(subset_female2017_treated.tail())
print(subset_female2018_treated.tail())
print(subset_male2016_treated.tail())
print(subset_male2017_treated.tail())
print(subset_male2018_treated.tail())

                  Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
1343370    Beth Thomas   F   SBD   NaN        226.80        136.08
1343371    Beth Poplin   F   SBD  45.5        190.51        145.15
1343372    Leah Benoit   F   SBD  28.5        199.58        124.74
1343373   Diane Gmiter   F   SBD   NaN        260.82        138.35
1343374  Alise Randall   F   SBD  26.5           NaN           NaN

         Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
1343370           181.44      NaN        XPC  2016         USA        OH
1343371           183.70    45-49        XPC  2016         USA        OH
1343372           174.63    24-34        XPC  2016         USA        OH
1343373           233.60      NaN        XPC  2016         USA        OH
1343374              NaN    24-34        XPC  2016         USA        OH

           MeetName   Region
1343370  PRO Finals  Midwest
1343371  PRO Finals  Midwest
1343372  PRO Finals  Midwest
1343373  PRO Finals  Midwest
1343374  PRO Finals  Midwest
                      Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
1343548   Alaina Hernandez   F   SBD   NaN        219.99        120.20
1343549  Jessica Bowersock   F   SBD  27.5        226.80        113.40
1343550     Kristen Wykoff   F   SBD   NaN        226.80         90.72
1343551    Cassandra Pinto   F   SBD  22.0        197.31         99.79
1343552     Jessica Chicke   F   SBD  36.5        181.44        104.33

         Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
1343548           217.72      NaN        XPC  2017         USA        OH
1343549           204.12    24-34        XPC  2017         USA        OH
1343550           213.19      NaN        XPC  2017         USA        OH
1343551           181.44    20-23        XPC  2017         USA        OH
1343552           181.44    35-39        XPC  2017         USA        OH

        MeetName   Region
1343548   Finals  Midwest
1343549   Finals  Midwest
1343550   Finals  Midwest
1343551   Finals  Midwest
1343552   Finals  Midwest
                      Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
1342564    Stephanie Smith   F   SBD   NaN        208.65        102.06
1342565      Barbara Coles   F   SBD  47.5        183.70        106.59
1342566  Jessica Bowersock   F   SBD  28.5        249.48        115.67
1342567   Alaina Hernandez   F   SBD   NaN        224.53        131.54
1342568       Jamie Kemper   F   SBD  32.5        238.14        129.27

         Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
1342564           215.46      NaN        XPC  2018         USA        OH
1342565           192.78    45-49        XPC  2018         USA        OH
1342566           226.80    24-34        XPC  2018         USA        OH
1342567           222.26      NaN        XPC  2018         USA        OH
1342568           215.46    24-34        XPC  2018         USA        OH

        MeetName   Region
1342564   Finals  Midwest
1342565   Finals  Midwest
1342566   Finals  Midwest
1342567   Finals  Midwest
1342568   Finals  Midwest
                   Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
1343427    Shane Church   M   SBD   NaN           NaN           NaN
1343428  Brian Billings   M   SBD  31.5           NaN           NaN
1343430    Jesse Luczyk   M   SBD  31.0           NaN           NaN
1343431     Steve Brock   M   SBD   NaN        430.91           NaN
1343432   Jayson McNett   M   SBD  35.0        458.13           NaN

         Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
1343427              NaN      NaN        XPC  2016         USA        OH
1343428              NaN    24-34        XPC  2016         USA        OH
1343430              NaN    24-34        XPC  2016         USA        OH
1343431              NaN      NaN        XPC  2016         USA        OH
1343432              NaN    35-39        XPC  2016         USA        OH

           MeetName   Region
1343427  PRO Finals  Midwest
1343428  PRO Finals  Midwest
1343430  PRO Finals  Midwest
1343431  PRO Finals  Midwest
1343432  PRO Finals  Midwest
                            Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
1343586            Stephen Davis   M   SBD   NaN        285.76        222.26
1343587         Terrance Gilbert   M   SBD  27.5        322.05        183.70
1343588             Kevin McHugh   M   SBD  27.0        385.55        208.65
1343589  Patrick Vincent Maguire   M   SBD   NaN        362.87        242.67
1343590              Doug Staley   M   SBD  27.5        347.00        185.97

         Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
1343586           340.19      NaN        XPC  2017         USA        OH
1343587           310.71    24-34        XPC  2017         USA        OH
1343588           344.73    24-34        XPC  2017         USA        OH
1343589           288.03      NaN        XPC  2017         USA        OH
1343590           306.17    24-34        XPC  2017         USA        OH

        MeetName   Region
1343586   Finals  Midwest
1343587   Finals  Midwest
1343588   Finals  Midwest
1343589   Finals  Midwest
1343590   Finals  Midwest
                   Name Sex Event   Age  Best3SquatKg  Best3BenchKg  \
1342591      JP Carroll   M   SBD  37.5        426.38        254.01
1342592    Kevin McHugh   M   SBD  28.0        410.50        213.19
1342593  Garrett Denham   M   SBD  33.5        367.41        222.26
1342594        Bill Lee   M   SBD  33.5        340.19        199.58
1342595  Benjamin Dewig   M   SBD   NaN        317.51        172.37

         Best3DeadliftKg AgeClass Federation  Date MeetCountry MeetState  \
1342591           353.80    35-39        XPC  2018         USA        OH
1342592           328.85    24-34        XPC  2018         USA        OH
1342593           333.39    24-34        XPC  2018         USA        OH
1342594           324.32    24-34        XPC  2018         USA        OH
1342595           340.19      NaN        XPC  2018         USA        OH

        MeetName   Region
1342591   Finals  Midwest
1342592   Finals  Midwest
1342593   Finals  Midwest
1342594   Finals  Midwest
1342595   Finals  Midwest

In [21]:
Pacific = ['WA', 'OR', 'CA']
Mountain = ['MT', 'ID', 'WY', 'NV', 'UT', 'CO', 'AZ', 'NM']
WestNorthCentral = ['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO']
WestSouthCentral = ['OK', 'TX', 'AR', 'LA']
EastNorthCentral = ['WI', 'MI', 'IL', 'IN', 'OH']
EastSouthCentral = ['KY', 'TN', 'MI', 'AL'] 
SouthAtlantic = ['WV', 'MD', 'DE', 'VA', 'NC', 'SC', 'GA', 'FL']
MiddleAtlantic = ['NY', 'PA', 'NJ']
NewEngland = ['ME', 'NH', 'VT', 'RI', 'MA', 'CT']

In [22]:
def conditions(s):
    if s['MeetState'] in Pacific :
        return 'Pacific'
    elif s['MeetState'] in Mountain :
        return 'Mountain'
    elif s['MeetState'] in WestNorthCentral :
        return 'WestNorthCentral'
    elif s['MeetState'] in WestSouthCentral :
        return 'WestSouthCentral'
    elif s['MeetState'] in EastNorthCentral :
        return 'EastNorthCentral'
    elif s['MeetState'] in EastSouthCentral :
        return 'EastSouthCentral'
    elif s['MeetState'] in SouthAtlantic :
        return 'SouthAtlantic'
    elif s['MeetState'] in MiddleAtlantic :
        return 'MiddleAtlantic'
    else :
        return 'NewEngland'

In [23]:
subset_female2016_treated['Division'] = subset_female2016_treated.apply(conditions, axis=1)
subset_female2017_treated['Division'] = subset_female2017_treated.apply(conditions, axis=1)
subset_female2018_treated['Division'] = subset_female2018_treated.apply(conditions, axis=1)
subset_male2016_treated['Division'] = subset_male2016_treated.apply(conditions, axis=1)
subset_male2017_treated['Division'] = subset_male2017_treated.apply(conditions, axis=1)
subset_male2018_treated['Division'] = subset_male2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [24]:
subset_female2016_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division
0,Angie Belk Terry,F,SBD,47.0,47.63,20.41,70.31,45-49,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic
1,Dawn Bogart,F,SBD,42.0,142.88,95.25,163.29,40-44,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic
5,Courtney Norris,F,SBD,28.0,170.10,77.11,145.15,24-34,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic
6,Maureen Clary,F,SBD,60.0,124.74,95.25,163.29,60-64,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic
8,Priscilla Sweat Pardue,F,SBD,52.0,120.20,54.43,108.86,50-54,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic

In [25]:
Red = ['ID', 'MT', 'WY', 'UT', 'AZ', 'ND', 'SD', 'NB', 'KS', 'OK', 'TX', 'MO', 'AR', 'LA', 'AL', 'MS', 'GA', 'SC', 'TN', 'WV', 'AK', 'KY']
Blue = ['WA', 'OR', 'CA', 'MN', 'IL', 'ME', 'VT', 'NH', 'NY', 'MA', 'NJ', 'RI', 'MD', 'DE', 'HI']
Pink = ['IN', 'NC']
Periwinkle = ['NV', 'CO', 'NM', 'WI', 'PA', 'VA']
Purple = ['IA', 'OH', 'FL']

In [26]:
def conditions(s):
    if s['MeetState'] in Red :
        return 'Red'
    elif s['MeetState'] in Blue :
        return 'Blue'
    elif s['MeetState'] in Pink :
        return 'Pink'
    elif s['MeetState'] in Periwinkle :
        return 'Periwinkle'
    else :
        return 'Purple'

In [27]:
subset_female2016_treated['Political'] = subset_female2016_treated.apply(conditions, axis=1)
subset_female2017_treated['Political'] = subset_female2017_treated.apply(conditions, axis=1)
subset_female2018_treated['Political'] = subset_female2018_treated.apply(conditions, axis=1)
subset_male2016_treated['Political'] = subset_male2016_treated.apply(conditions, axis=1)
subset_male2017_treated['Political'] = subset_male2017_treated.apply(conditions, axis=1)
subset_male2018_treated['Political'] = subset_male2018_treated.apply(conditions, axis=1)

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\M B Brooks\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [28]:
subset_female2016_treated.head()

,Name,Sex,Event,Age,Best3SquatKg,Best3BenchKg,Best3DeadliftKg,AgeClass,Federation,Date,MeetCountry,MeetState,MeetName,Region,Division,Political
0,Angie Belk Terry,F,SBD,47.0,47.63,20.41,70.31,45-49,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic,Pink
1,Dawn Bogart,F,SBD,42.0,142.88,95.25,163.29,40-44,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic,Pink
5,Courtney Norris,F,SBD,28.0,170.10,77.11,145.15,24-34,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic,Pink
6,Maureen Clary,F,SBD,60.0,124.74,95.25,163.29,60-64,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic,Pink
8,Priscilla Sweat Pardue,F,SBD,52.0,120.20,54.43,108.86,50-54,365Strong,2016,USA,NC,Junior & Senior National Powerlifting Champion...,South,SouthAtlantic,Pink

In [29]:
print(subset_male2016_treated.shape)
print(subset_male2017_treated.shape)
print(subset_male2018_treated.shape)
print(subset_female2016_treated.shape)
print(subset_female2017_treated.shape)
print(subset_female2018_treated.shape)

(56199, 16)
(58951, 16)
(60086, 16)
(32429, 16)
(35417, 16)
(38248, 16)

In [30]:
xf16 = subset_female2016_treated[-subset_female2016_treated['MeetState'].isna()] 
xf17 = subset_female2017_treated[-subset_female2017_treated['MeetState'].isna()]
xf18 = subset_female2018_treated[-subset_female2018_treated['MeetState'].isna()] 
xm16 = subset_male2016_treated[-subset_male2016_treated['MeetState'].isna()]
xm17 = subset_male2017_treated[-subset_male2017_treated['MeetState'].isna()]
xm18 = subset_male2018_treated[-subset_male2018_treated['MeetState'].isna()]

# 15. Detecting and Removing Missing Values

The variable $x$ is being assigned to the subset where $x$ is a null value in the *MeetState* column.

In [31]:
print(xf16.shape)
print(xf17.shape)
print(xf18.shape)
print(xm16.shape)
print(xm17.shape)
print(xm18.shape)

(31525, 16)
(34924, 16)
(37989, 16)
(54633, 16)
(58069, 16)
(59486, 16)

# 16. Testing for Missing Values Removed

Printing the $xf$ and $xm$ variables and adding the dot notation $shape$ returns the number of rows and columns that remain after applying the $isna$ operation.

In [37]:
pd.concat([subset_male2016_treated, subset_male2017_treated, subset_male2018_treated, 
           subset_female2016_treated, subset_female2017_treated, subset_female2018_treated], 
          axis=1).to_csv('all_lifters_years.csv')

# 17. Notebook as CSV Output

Running the cell above will input the data for each subset into a csv output file.